import { AMAZE_API_NAMES } from "@app/core/backend/api.constants";

export const AMAZE_API_URLS : Record<string, string> = {

	// Entity Info API url
	[AMAZE_API_NAMES.GET_ENTITY_INFO]                                      : "/entity/{entityType}/{entitykey}",

	// Catalog Related API names
	[AMAZE_API_NAMES.GET_CATALOGS]                                         : "/catalogs/previewDetails?aggregationLevel=catalog",
	[AMAZE_API_NAMES.GET_CATALOG]                                          : "/catalogs/{catalogId}",
	[AMAZE_API_NAMES.GET_CATALOG_BASIC_DETAILS]                            : "/catalogs/previewDetails?aggregationLevel=basic",
	[AMAZE_API_NAMES.GET_CATALOG_DOMAIN_DETAILS]                           : "/catalogs/previewDetails?aggregationLevel=domain",
	[AMAZE_API_NAMES.CREATE_CATALOG]                                       : "/catalogs",
	[AMAZE_API_NAMES.DELETE_CATALOG]                                       : "/catalogs/{catalogId}",
	[AMAZE_API_NAMES.GET_ALL_CATALOGS]                                     : "/allCatalogs",

	// Domain Related API urls
	[AMAZE_API_NAMES.GET_DOMAINS]                                          : "/catalogs/{catalogId}/domain",
	[AMAZE_API_NAMES.ADD_DOMAIN]                                           : "/catalogs/{catalogId}/domain",
	[AMAZE_API_NAMES.UPDATE_DOMAIN]                                        : "/catalogs/{catalogId}/domain",
	[AMAZE_API_NAMES.DELETE_DOMAIN]                                        : "/catalogs/{catalogId}/domain/{domainId}",

	// Style Guide Related API urls
	[AMAZE_API_NAMES.GET_STYLE_GUIDE]                                      : "/catalogs/{catalogId}/styleGuide",
	[AMAZE_API_NAMES.GET_STYLE_GUIDE_REPORT]                               : "/catalogs/{catalogId}/styleGuide/checkResult",
	[AMAZE_API_NAMES.GET_STYLE_GUIDE_REPORT_COUNT]                         : "/catalogs/{catalogId}/styleGuide/checkResult/count",
	[AMAZE_API_NAMES.CREATE_STYLE_GUIDE]                                   : "/catalogs/{catalogId}/styleGuide",
	[AMAZE_API_NAMES.UPDATE_STYLE_GUIDE]                                   : "/catalogs/{catalogId}/styleGuide",
	[AMAZE_API_NAMES.DELETE_STYLE_GUIDE]                                   : "/catalogs/{catalogId}/styleGuide",
	[AMAZE_API_NAMES.DELETE_STYLE_GUIDE_REPORT]                            : "/catalogs/{catalogId}/styleGuide/checkResult",
	[AMAZE_API_NAMES.DOWNLOAD_STYLE_GUIDE_REPORT]                          : "/catalogs/{catalogId}/styleGuide/downloadReport",
	[AMAZE_API_NAMES.FIX_STYLE_GUIDE]                                      : "/catalogs/{catalogId}/styleGuide/fix",
	[AMAZE_API_NAMES.PERFORM_CHECK_STYLE_GUIDE]                            : "/catalogs/{catalogId}/styleGuide/performCheck",

	// Global Search Related API urls
	[AMAZE_API_NAMES.CATALOG_GLOBAL_SEARCH]                                : "/catalogs/{catalogId}/globalSearch",
	[AMAZE_API_NAMES.SKU_GLOBAL_SEARCH]                                    : "/catalogs/{catalogId}/globalSkuSearch",

	// Catalog Nodes Related API urls
	[AMAZE_API_NAMES.GET_CATALOG_NODES]                                    : "/catalogs/{catalogId}/nodes?depth]:{depth}&domain]:{domain}",
	[AMAZE_API_NAMES.GET_CATALOG_CHILD_NODES]                              : "/catalogs/{catalogId}/nodes?depth]:{depth}&nodeId]:{nodeId}&domain]:{domain}",
	[AMAZE_API_NAMES.GET_CATALOG_NODES_LIST]                               : "/catalogs/{catalogId}/nodes",
	[AMAZE_API_NAMES.GET_CATALOG_NODES_IN_ORDER]                           : "/catalogs/{catalogId}/nodes/reorderAlphabetically?domain]:{domain}",
	[AMAZE_API_NAMES.GET_CATALOG_NODES_SEARCH]                             : "/catalogs/{catalogId}/searchNodes",
	[AMAZE_API_NAMES.GET_CATALOG_NODES_SEARCH_HIERARCHY]                   : "/catalogs/{catalogId}/nodes/{nodeId}/getParentIds",
	[AMAZE_API_NAMES.GET_CATALOG_NODE_DETAILS]                             : "/catalogs/{catalogId}/nodes/{nodeId}",

	// Taxonomy Related API urls
	[AMAZE_API_NAMES.ADD_NODES]                                            : "/catalogs/{catalogId}/nodes?domain]:{domain}",
	[AMAZE_API_NAMES.UPDATE_NODES]                                         : "/catalogs/{catalogId}/nodes?domain]:{domain}",
	[AMAZE_API_NAMES.MOVE_NODES]                                           : "/catalogs/{catalogId}/nodes/{nodeId}/move?domain]:{domain}",
	[AMAZE_API_NAMES.REORDER_NODES]                                        : "/catalogs/{catalogId}/nodes/{nodeId}/reorder?domain]:{domain}",
	[AMAZE_API_NAMES.DELETE_NODES]                                         : "/catalogs/{catalogId}/nodes/{nodeId}?domain]:{domain}",
	[AMAZE_API_NAMES.COPY_TAXONOMY_STRUCTURE]                              : "/catalogs/{catalogId}/domain/copyTaxonomyStructure",

	// SKU Related API urls
	[AMAZE_API_NAMES.GET_SKU]                                              : "/catalogs/{catalogId}/skus/{skuId}",
	[AMAZE_API_NAMES.GET_SKUS]                                             : "/catalogs/{catalogId}/skus;type]:EQ]:SKU",
	[AMAZE_API_NAMES.GET_SKUS_BY_NODE]                                     : "/catalogs/{catalogId}/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.ADD_SKUS]                                             : "/catalogs/{catalogId}/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.CREATE_SKUS]                                          : "/catalogs/{catalogId}/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.EDIT_SKUS]                                            : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.UPDATE_SKUS]                                          : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.DELETE_SKUS]                                          : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.MOVE_SKUS]                                            : "/catalogs/{catalogId}/nodes/{targetNodeId}/skus",
	[AMAZE_API_NAMES.MIRROR_SKUS]                                          : "/catalogs/{catalogId}/domain/mirrorSkus",
	[AMAZE_API_NAMES.REMOVE_MIRROR_SKUS]                                   : "/catalogs/{catalogId}/domain/{domainId}/mirrorSkus",
	[AMAZE_API_NAMES.CROSS_LIST_SKUS]                                      : "/catalogs/{catalogId}/crossListing/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.GET_CROSSLIST_SKUS]                                   : "/catalogs/{catalogId}/crossListing/nodes/{nodeId}/skus?count]:true",
	[AMAZE_API_NAMES.ADD_CROSSLIST_SKUS]                                   : "/catalogs/{catalogId}/skuCrossListing",
	[AMAZE_API_NAMES.REMOVE_CROSSLIST_SKUS]                                : "/catalogs/{catalogId}/crossListing/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.REMOVE_SKU_CROSS_LISTING]                             : "/catalogs/{catalogId}/crossListing/nodes/{nodeId}/skus",
	[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES]                                   : "/catalogs/{catalogId}/domains/{domainId}/attributes",
	[AMAZE_API_NAMES.GET_SKU_IDS]                                          : "/catalogs/{catalogId}/skuIds",

	// SKU Relationship Related API names
	// Related SKUs Related API names
	// SKUs-UOM converison API names
	// SKU Authoring API names
	// SKU Validation API names
	// SCHEMA related API names
	// Product Family related API names
	// Attribute related API names
	// Attribute Group related API names
	// Attribute MetaTag Group related API names
	// UOMs related API names
	// Digital Assets related API names
	// Vision API related API names
	// Digital Assets Import related API names
	// Digital Assets Metadata related API names
	// Assets Linkage and Delinkage (Taxonomy) related API names
	// Assets Linkage and Delinkage (SKU) related API names
	// Assets Linkage and Delinkage (Attribute) related API names
	// Assets Linkage and Delinkage (SKU Meta Attribute) related API names
	// Assets Bulk Edit (Photos) related API names
	// User management related API names
	// Role management related API names
	// User Group management related API names
	// Privileges management related API names
	// Review related API names
	// Reject review request modifications related API names
	// Reports related API names
	// Validation Failure management related API names
	// Import Templates related API names
	// Hybrid Import Templates related API names
	// Imports related API names
	// Exports related API names
	// Export Templates related API names
	// Amazon Templates related API names
	// Grainger Templates related API names
	// Amaze parameters related API
	// Authentication related API names
	// Aamze-bridge Synchronization related API names
	// Realtime Sync Linkages related API names
	// Product Detail Page related API names
	// Taxonomy Metadata related API names
	// Bulk Download Digital Assets related API names
	// Advance SKU Search (Product Search) related API names
	// CKB related API names
	// Connectors related API names
	// Magento 2 Connector related API names
	// Public Apis Module related API names
	// Formula Master related API names
	// Attribute Value Lock related API names
	// Domain related API
	// Customers related API
	// Dashboard related API names
	// Products Listing related API names
	// Product 360 View related API names
	// Marketing Recommed=ndation related API
	// Assortments related API names

	[AMAZE_API_NAMES.ADD_ATTRIBUTE_IN_GROUPS]                              : "/catalogs/{catalogId}/attributeGroups/{attributeGroupId}/attributes-add",
	[AMAZE_API_NAMES.ADD_ATTRIBUTE_META_ATTRIBUTE]                         : "/attributeMetaAttribute",
	[AMAZE_API_NAMES.ADD_ATTRIBUTE_METATAG]                                : "/attributeMetatag",
	[AMAZE_API_NAMES.ADD_ATTRIBUTES]                                       : "/catalogs/{catlogId}/attributes",
	[AMAZE_API_NAMES.ADD_DIGITAL_ASSETS]                                   : "/digitalAssets",
	[AMAZE_API_NAMES.ADD_FILE]                                             : "/catalogs/{catalogId}/imports/{importId}/importFiles",
	[AMAZE_API_NAMES.ADD_META_ATTRIBUTES]                                  : "/addMissingDaMetaAttributesAndGetKeys",
	[AMAZE_API_NAMES.ADD_META_TAGS]                                        : "/addMissingDaMetaTagsAndGetKeys",
	[AMAZE_API_NAMES.ADD_NOTE_TO_REPORT]                                   : "/catalogs/{catalogId}/reports/{reportCode}/note",
	[AMAZE_API_NAMES.ADD_PHOTO_EDIT_TEMPLATE]                              : "/daPhotoEditTemplates",
	[AMAZE_API_NAMES.ADD_PRIVILEGE_TO_ROLE]                                : "/security/roles/{roleId}/privileges",
	[AMAZE_API_NAMES.ADD_RELATED_SKUS]                                     : "/catalogs/{catalogId}/relatedSkus",
	[AMAZE_API_NAMES.ADD_ROLES_TO_USER]                                    : "/security/users/{userId}/roles",
	[AMAZE_API_NAMES.ADD_SCHEMAS]                                          : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes",
	[AMAZE_API_NAMES.ADD_UOMS]                                             : "/uoms",
	[AMAZE_API_NAMES.ADD_USER_GROUPS]                                      : "/security/userGroups",
	[AMAZE_API_NAMES.ADD_USERS_TO_ROLE]                                    : "/security/roles/{roleId}/users",
	[AMAZE_API_NAMES.ASSIGN_ROLES_TO_USER_GROUPS]                          : "/security/userGroups/{userGroupId}/roles",
	[AMAZE_API_NAMES.ASSIGN_USERS_TO_USER_GROUPS]                          : "/security/userGroups/{userGroupId}/users",
	[AMAZE_API_NAMES.ATTACH_SKU_TO_PRODUCT_FAMILIES]                       : "/catalogs/{catalogId}/nodes/{nodeId}/productFamilies/{productFamilyId}/skuLinkage-create",
	[AMAZE_API_NAMES.ATTRIBUTES_FOR_DIGITAL_ASSETS]                        : "/attributesForDAs",
	[AMAZE_API_NAMES.ATTRIBUTES_SEARCH]                                    : "/catalogs/{catalogId}/attributes",
	[AMAZE_API_NAMES.BULK_UPDATE_DA_METADATA]                              : "/bulkUpdateDAs",
	[AMAZE_API_NAMES.CASCADE_VALUE_TO_SKUS]                                : "/catalogs/{catalogId}/nodes/{nodeId}/productFamily/rollAttributeValues",
	[AMAZE_API_NAMES.CATALOG_DOMAIN_REVIEW_PRIVILEGES]                     : "/security/review/privileges",
	[AMAZE_API_NAMES.CHECK_LOV_SUGGESTIONS]                                : "/catalogs/{catalogId}/reports/{reportCode}/taxonomies",
	[AMAZE_API_NAMES.CHECK_PENDING_TAXONOMY_REVIEW]                        : "/catalogs/{catalogId}/nodes/{nodeId}/operation/{operationName}/checkPendingReview",
	[AMAZE_API_NAMES.COPY_SKU_ATTRIBUTES]                                  : "/catalogs/{catalogId}/skus/{skuId}/attributes/{attributeId}/copy",
	[AMAZE_API_NAMES.CREATE_ATTRIBUTE_DIGITAL_ASSET_LINK]                  : "/catalogs/{catalogId}/attributeLinks/",
	[AMAZE_API_NAMES.CREATE_ATTRIBUTE_GROUPS]                              : "/catalogs/{catalogId}/attributeGroups",
	[AMAZE_API_NAMES.CREATE_BATCH_PROCESS]                                 : "/daPhotoEditBatchProcess",
	[AMAZE_API_NAMES.CREATE_EXPORTS]                                       : "/catalogs/{catalogId}/exports",
	[AMAZE_API_NAMES.CREATE_HYBRID_TEMPLATE]                               : "/importHybridTemplates",
	[AMAZE_API_NAMES.CREATE_IMPORT_TEMPLATES]                              : "/catalogs/{catalogId}/importTemplates",
	[AMAZE_API_NAMES.CREATE_IMPORTS]                                       : "/catalogs/{catalogId}/imports",
	[AMAZE_API_NAMES.CREATE_ROLE]                                          : "/security/roles",
	[AMAZE_API_NAMES.CREATE_SKU_DIGITAL_ASSET_LINK]                        : "/catalogs/{catalogId}/skuLinks",
	[AMAZE_API_NAMES.CREATE_SKU_FROM_EXTERNAL_SOURCES]                     : "/catalogs/{catalogId}/skuAttributes",
	[AMAZE_API_NAMES.CREATE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS]        : "/catalogs/{catalogId}/skuLinks/",
	[AMAZE_API_NAMES.CREATE_SKU_RELATIONSHIPS]                             : "/skuRelationships",
	[AMAZE_API_NAMES.CREATE_TAXONOMY_DIGITAL_ASSET_LINK]                   : "/catalogs/{catalogId}/taxonomyLinks",
	[AMAZE_API_NAMES.CREATE_USER]                                          : "/security/users",
	[AMAZE_API_NAMES.DA_META_ATTRIBUTES]                                   : "/daMetaAttributes",
	[AMAZE_API_NAMES.DA_METATAGS]                                          : "/daMetatags",
	[AMAZE_API_NAMES.DELETE_ATTRIBUTE]                                     : "/catalogs/{catlogId}/attributes/{attributeId}",
	[AMAZE_API_NAMES.DELETE_ATTRIBUTE_DIGITAL_ASSET_LINK]                  : "/catalogs/{catalogId}/attributeLinks",
	[AMAZE_API_NAMES.DELETE_ATTRIBUTE_META_ATTRIBUTE]                      : "/attributeMetaAttribute/{metaAttributeId}",
	[AMAZE_API_NAMES.DELETE_ATTRIBUTE_METATAG]                             : "/attributeMetatag/{metatagId}",
	[AMAZE_API_NAMES.DELETE_DIGITAL_ASSETS]                                : "/digitalAssets",
	[AMAZE_API_NAMES.DELETE_EXPORT]                                        : "/catalogs/{catalogId}/exports/{id}",
	[AMAZE_API_NAMES.DELETE_FILE]                                          : "/catalogs/{catalogId}/imports/{importId}/importFiles/{importFileId}",
	[AMAZE_API_NAMES.DELETE_HYBRID_TEMPLATE]                               : "/importHybridTemplates/{templateId}",
	[AMAZE_API_NAMES.DELETE_IMPORT]                                        : "/catalogs/{catalogId}/imports/{id}",
	[AMAZE_API_NAMES.DELETE_IMPORT_TEMPLATES]                              : "/catalogs/{catalogId}/importTemplates/{id}",
	[AMAZE_API_NAMES.DELETE_PHOTO_EDIT_TEMPLATE]                           : "/daPhotoEditTemplates/{templateId}",
	[AMAZE_API_NAMES.DELETE_RELATED_SKUS]                                  : "/catalogs/{catalogId}/nodes/{nodeId}/skus/{skuId}/relatedSkus",
	[AMAZE_API_NAMES.DELETE_ROLE]                                          : "/security/roles/{roleId}",
	[AMAZE_API_NAMES.DELETE_SCHEMAS]                                       : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes",
	[AMAZE_API_NAMES.DELETE_SKU_DIGITAL_ASSET_LINK]                        : "/catalogs/{catalogId}/skuLinks",
	[AMAZE_API_NAMES.DELETE_SKU_FROM_EXTERNAL_SOURCES]                     : "/catalogs/{catalogId}/skuAttributes",
	[AMAZE_API_NAMES.DELETE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS]        : "/catalogs/{catalogId}/skuLinks/links/{linkId}",
	[AMAZE_API_NAMES.DELETE_SKU_RELATIONSHIPS]                             : "/skuRelationships/{relationshipId}",
	[AMAZE_API_NAMES.DELETE_TAXONOMY_DIGITAL_ASSET_LINK]                   : "/catalogs/{catalogId}/taxonomyLinks",
	[AMAZE_API_NAMES.DELETE_UOM]                                           : "/uoms/{uomId}",
	[AMAZE_API_NAMES.DELETE_USER]                                          : "/security/users/{userId}",
	[AMAZE_API_NAMES.DELETE_USER_GROUPS]                                   : "/security/userGroups/{userGroupId}",
	[AMAZE_API_NAMES.DETACH_SKU_TO_PRODUCT_FAMILIES]                       : "/catalogs/{catalogId}/nodes/{nodeId}/skuLinkage-remove",
	[AMAZE_API_NAMES.DOWNLOAD_ASSET_MANIFEST_REPORT]                       : "/digitalAssetManifestReport",
	[AMAZE_API_NAMES.DOWNLOAD_ASSETS]                                      : "/digitalAssets/download",
	[AMAZE_API_NAMES.DOWNLOAD_EXPORT_FILE]                                 : "/catalogs/{catalogId}/exports/{exportId}/exportFiles/{exportFileId}",
	[AMAZE_API_NAMES.DOWNLOAD_EXPORT_SAMPLE]                               : "/exportFileTypes/{id}",
	[AMAZE_API_NAMES.DOWNLOAD_IMPORT_FILE]                                 : "/catalogs/{catalogId}/imports/{importId}/importFiles/{importFileId}",
	[AMAZE_API_NAMES.DOWNLOAD_REPORT]                                      : "/catalogs/{catalogId}/reports/{reportCode}/data/download",
	[AMAZE_API_NAMES.EDIT_ATTRIBUTE_META_ATTRIBUTE]                        : "/attributeMetaAttribute",
	[AMAZE_API_NAMES.EDIT_ATTRIBUTE_METATAG]                               : "/attributeMetatag",
	[AMAZE_API_NAMES.EDIT_ATTRIBUTES]                                      : "/catalogs/{catlogId}/attributes",
	[AMAZE_API_NAMES.EDIT_PHOTO_EDIT_TEMPLATE]                             : "/daPhotoEditTemplates",
	[AMAZE_API_NAMES.EDIT_PRODUCT_FAMILY_TITLE]                            : "/catalogs/{catalogId}/skus/{productFamilyId}/title-update",
	[AMAZE_API_NAMES.EDIT_SCHEMAS]                                         : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes",
	[AMAZE_API_NAMES.EDIT_UOMS]                                            : "/uoms",
	[AMAZE_API_NAMES.EDIT_USER_GROUPS]                                     : "/security/userGroups/{userGroupId}",
	[AMAZE_API_NAMES.EXECUTE_PF_RECOMMENDATION]                            : "/catalogs/{catalogId}/nodes/{nodeId}/productFamily/recommendation",
	[AMAZE_API_NAMES.EXECUTE_REPORT]                                       : "/catalogs/{catalogId}/reports/{reportCode}/execute",
	[AMAZE_API_NAMES.EXTERNAL_SOURCES_AUDIT]                               : "/catalogs/{catalogId}/skuAttributes/audit",
	[AMAZE_API_NAMES.FETCH_P_1_DRILLDOWN_REPORT]                           : "/catalogs/{catalogId}/reports/{reportCode}/skus",
	[AMAZE_API_NAMES.FETCH_P_7_DRILLDOWN_REPORT]                           : "/catalogs/{catalogId}/reports/{reportCode}/drilldown/data",
	[AMAZE_API_NAMES.FETCH_REPORT]                                         : "/catalogs/{catalogId}/reports/{reportCode}/data",
	[AMAZE_API_NAMES.FIX_P_12]                                             : "/catalogs/{catalogId}/reports/{reportCode}/fixExtraneousSpaces",
	[AMAZE_API_NAMES.FIX_REPORT]                                           : "/catalogs/{catalogId}/reports/{reportCode}/skus",
	[AMAZE_API_NAMES.FIX_REPORT_S_10_CONSTRAINTS]                          : "/catalogs/{catalogId}/reports/{reportCode}/schemas/constraints",
	[AMAZE_API_NAMES.FIX_REPORT_S_10_LOVS]                                 : "/catalogs/{catalogId}/reports/{reportCode}/schemas/lovs",
	[AMAZE_API_NAMES.FIX_REPORT_S_10_UOMS]                                 : "/catalogs/{catalogId}/reports/{reportCode}/schemas/uoms",
	[AMAZE_API_NAMES.FIX_REPORT_T_1]                                       : "/catalogs/{catalogId}/reports/{reportCode}/taxonomies",
	[AMAZE_API_NAMES.GET_ALL_REPORTS]                                      : "/catalogs/{catalogId}/reports",
	[AMAZE_API_NAMES.GET_ASSET_TAGS_LIST]                                  : "/digitalAssets/tags",
	[AMAZE_API_NAMES.GET_ASSET_VISION_INFO]                                : "/digitalAssets/{digitalAssetId}/recognitionInfo",
	[AMAZE_API_NAMES.GET_ASSET_VISION_INFO_COUNT]                          : "/daPhotoBatchVisionInfoProcess/count",
	[AMAZE_API_NAMES.GET_ATTRIBUTE]                                        : "/catalogs/{catalogId}/attributes/{attributeId}",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ATTRIBUTE]       : "/catalogs/{catalogId}/attributeLinks/attributes/{attributeId}",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET]   : "/catalogs/{catalogId}/attributeLinks/digitalAssets/{digitalAssetId}",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ID]              : "/catalogs/{catalogId}/attributeLinks/links/{linkId}",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_GROUPS]                                 : "/catalogs/{catalogId}/attributeGroups",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_META_ATTRIBUTE]                         : "/attributeMetaAttribute",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_METATAG]                                : "/attributeMetatag",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_METATAG_RELEVANCE]                      : "/metatagRelevance",
	[AMAZE_API_NAMES.GET_ATTRIBUTES]                                       : "/catalogs/{catalogId}/attributes",
	[AMAZE_API_NAMES.GET_ATTRIBUTES_IN_GROUPS]                             : "/catalogs/{catalogId}/attributeGroups/{attributeGroupId}/attributes",
	[AMAZE_API_NAMES.GET_BATCH_PROCESS_PROCESSED_ASSETS]                   : "/daPhotoEditBatchProcess/{templateId}/units",
	[AMAZE_API_NAMES.GET_BME_CAT_VERSIONS]                                 : "/bmecatVersion",
	[AMAZE_API_NAMES.GET_CHILD_PRODUCT_FAMILIES]                           : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.GET_CONVERSION_FORMULA]                               : "/uoms/{baseUomId}/targetUoms/{targetUomId}/conversionFormula",
	[AMAZE_API_NAMES.GET_COPIED_SCHEMAS]                                   : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes?limit]:{limit}&offset]:{offset}&count]:{count}",
	[AMAZE_API_NAMES.GET_DA_COUNTS_FOR_ADVANCED_FILTER]                    : "/getDaCountsForAdvancedFilter",
	[AMAZE_API_NAMES.GET_DA_META_ATTRIBUTES]                               : "/daMetaAttributes;digitalAssetMetaAttributeName]:LK]:{searchTerm}",
	[AMAZE_API_NAMES.GET_DA_META_TAGS]                                     : "/daMetatags;digitalAssetMetatagName]:LK]:{searchTerm}",
	[AMAZE_API_NAMES.GET_DIGITAL_ASSET]                                    : "/digitalAssets/{assetId}",
	[AMAZE_API_NAMES.GET_DIGITAL_ASSET_FOR_IMPORT]                         : "/digitalAssets/import",
	[AMAZE_API_NAMES.GET_DIGITAL_ASSET_FOR_IMPORT_DETAISL]                 : "/digitalAssets/import/{importId}/details",
	[AMAZE_API_NAMES.GET_DIGITAL_ASSETS]                                   : "/digitalAssets",
	[AMAZE_API_NAMES.GET_EXECUTION_HISTORY]                                : "/catalogs/{catalogId}/reports/{reportCode}/executionHistory",
	[AMAZE_API_NAMES.GET_EXPORT]                                           : "/catalogs/{catalogId}/exports/{id}",
	[AMAZE_API_NAMES.GET_EXPORT_FILE_TYPES]                                : "/exportFileTypes",
	[AMAZE_API_NAMES.GET_EXPORT_READINESS]                                 : "/exportReadiness/{skuId}",
	[AMAZE_API_NAMES.GET_EXPORT_TEMPLATES]                                 : "/exportTemplates",
	[AMAZE_API_NAMES.GET_EXPORTS]                                          : "/exports",
	[AMAZE_API_NAMES.GET_EXTERNAL_SOURCES]                                 : "/catalogs/{catalogId}/nodes/{nodeId}/externalSources",
	[AMAZE_API_NAMES.GET_GLOBAL_PRIVILEGES]                                : "/security/global/privileges",
	[AMAZE_API_NAMES.GET_GRAINGER_ITERATION_FAILED_SKUS]                   : "/catalogs/{catalogId}/exports/{exportId}/exportIterationFailedSkus",
	[AMAZE_API_NAMES.GET_GRAINGER_SKU_UPDATE_COUNT]                        : "/graingerTemplates/skuUpdateCount",
	[AMAZE_API_NAMES.GET_HYBRID_TEMPLATES]                                 : "/importHybridTemplates",
	[AMAZE_API_NAMES.GET_IMPORT]                                           : "/catalogs/{catalogId}/imports/{id}",
	[AMAZE_API_NAMES.GET_IMPORT_ERROR_LOG]                                 : "/digitalAssets/import/{importId}/downloadError",
	[AMAZE_API_NAMES.GET_IMPORT_FILE_TYPES]                                : "/importFileTypes",
	[AMAZE_API_NAMES.GET_IMPORT_TEMPLATES]                                 : "/importTemplates",
	[AMAZE_API_NAMES.GET_IMPORTS]                                          : "/imports",
	[AMAZE_API_NAMES.GET_ITERATION_FAILURE_DESCRIPTION]                    : "/failedSkusDescriptions",
	[AMAZE_API_NAMES.GET_LATEST_EXPORT_DATE]                               : "/catalogs/{catalogId}/exports/latestExportDates",
	[AMAZE_API_NAMES.GET_LOV_SUGGESTIONS]                                  : "/catalogs/{catalogId}/attributes/{attributeId}/lovs",
	[AMAZE_API_NAMES.GET_LOVS_FOR_ATTR]                                    : "/catalogs/{catalogId}/attributes/{attributeId}/lovs",
	[AMAZE_API_NAMES.GET_PRODUCT_FAMILY_TREE_HIERARCHY]                    : "/catalogs/{catalogId}/nodes/{nodeId}/productFamilies/{pfId}/getParentIds",
	[AMAZE_API_NAMES.GET_PHOTO_EDIT_TEMPLATE]                              : "/daPhotoEditTemplates/{templateId}",
	[AMAZE_API_NAMES.GET_PHOTO_EDIT_TEMPLATES_LIST]                        : "/daPhotoEditTemplates",
	[AMAZE_API_NAMES.GET_PRE_SIGNED_URL]                                   : "/preSignedUrl",
	[AMAZE_API_NAMES.GET_PRIVILEGE_CODES_FOR_ROLE]                         : "/security/roles/{roleId}/privilegeCodes",
	[AMAZE_API_NAMES.GET_PRIVILEGE_CODES_FOR_USER]                         : "/security/users/{userId}/privilegeCodes",
	[AMAZE_API_NAMES.GET_PRIVILEGES_FOR_ROLE]                              : "/security/roles/{roleId}/privileges",
	[AMAZE_API_NAMES.GET_PRIVILEGES_FOR_USER]                              : "/security/users/{userId}/privileges",
	[AMAZE_API_NAMES.GET_PRODUCT_FAMILIES]                                 : "/catalogs/{catalogId}/skus;type]:EQ]:ProductFamily",
	[AMAZE_API_NAMES.GET_PRODUCT_FAMILY]                                   : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.GET_PRODUCT_FAMILIES_BY_ATTRIBUTE]                    : "/catalogs/{catalogId}/skuAttributes",
	[AMAZE_API_NAMES.GET_RELATED_SKUS]                                     : "/catalogs/{catalogId}/nodes/{nodeId}/skus/{skuId}/relatedSkus",
	[AMAZE_API_NAMES.GET_RESTRICTIONS]                                     : "/restrictions",
	[AMAZE_API_NAMES.GET_REVIEW]                                           : "/catalogs/{catalogId}/reviews/{reviewId}",
	[AMAZE_API_NAMES.GET_REVIEW_ACTIONS]                                   : "/entities/{entity}/reviewActions",
	[AMAZE_API_NAMES.GET_REVIEW_COUNTS]                                    : "/catalogs/{catalogId}/reviews/count",
	[AMAZE_API_NAMES.GET_REVIEW_HISTORY]                                   : "/catalogs/{catalogId}/reviews/{reviewId}",
	[AMAZE_API_NAMES.GET_REVIEW_RESTRICTIONS_MATRIX]                       : "/reviewRestrictions",
	[AMAZE_API_NAMES.GET_REVIEW_STATUSES]                                  : "/reviewStatuses",
	[AMAZE_API_NAMES.GET_REVIEWS_LIST]                                     : "/catalogs/{catalogId}/reviews",
	[AMAZE_API_NAMES.GET_ROLES]                                            : "/security/roles",
	[AMAZE_API_NAMES.GET_ROLES_FOR_USER]                                   : "/security/users/{userId}/roles",
	[AMAZE_API_NAMES.GET_SCHEMA_ATTR_ON_MULTIPLE_NODE]                     : "/catalogs/{catalogId}/commonSchemaAttributes",
	[AMAZE_API_NAMES.GET_SCHEMA_ATTRIBUTES]                                : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes/attributes",
	[AMAZE_API_NAMES.GET_SCHEMAS]                                          : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes",
	[AMAZE_API_NAMES.GET_SEARCHED_CONDITION]                               : "/conditionNameAndIds",
	[AMAZE_API_NAMES.GET_SINGLE_IMPORT_TEMPLATES]                          : "/catalogs/{catalogId}/importTemplates/{id}",
	[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES_FOR_FILTERING]                     : "/catalogs/{catalogId}/failedValidationAttributes",
	[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET]         : "/catalogs/{catalogId}/skuLinks/digitalAssets/{digitalAssetId}",
	[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_ID]                    : "/catalogs/{catalogId}/skuLinks/links/{linkId}",
	[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_SKU]                   : "/catalogs/{catalogId}/skuLinks/skus/{skuId}",
	[AMAZE_API_NAMES.GET_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS]           : "/catalogs/{catalogId}/skuLinks/links/{linkId}/metaAttribute",
	[AMAZE_API_NAMES.GET_SKU_RELATIONSHIPS]                                : "/skuRelationships",
	[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES]                          : "/catalogs/{catalogId}/nodes/{nodeId}/skus/{skuId}/validationFailures",
	[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES_FOR_TAXONOMY]             : "/catalogs/{catalogId}/nodes/{nodeId}/skuValidationFailures",
	[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES_SUMMARY_FOR_TAXONOMY]     : "/catalogs/{catalogId}/nodes/{nodeId}/skuValidationFailures/summary",
	[AMAZE_API_NAMES.GET_SKUS_RECOMMENDED_DA]                              : "/digitalAssets/recommendations",
	[AMAZE_API_NAMES.GET_STATIC_HTML]                                      : "/getUrlHtml?url]:{url}",
	[AMAZE_API_NAMES.GET_TARGET_UOM]                                       : "/catalogs/{catalogId}/attributes/{attributeId}/uoms",
	[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET]    : "/catalogs/{catalogId}/taxonomyLinks/digitalAssets/{digitalAssetId}",
	[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_ID]               : "/catalogs/{catalogId}/taxonomyLinks/links/{linkId}",
	[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_TAXONOMY]         : "/catalogs/{catalogId}/taxonomyLinks/nodes/{taxonomyId}",
	[AMAZE_API_NAMES.GET_TAXONOMY_REPORT]                                  : "/catalogs/{catalogId}/domain/{domain}/taxonomyDetailsReport",
	[AMAZE_API_NAMES.GET_UNIQUE_ERROR_MESSAGES]                            : "/digitalAssets/import/{importId}/getUniqueErrors",
	[AMAZE_API_NAMES.GET_UOMS]                                             : "/uoms",
	[AMAZE_API_NAMES.GET_UOMS_CATEGORIES]                                  : "/uomCategories",
	[AMAZE_API_NAMES.GET_UOMS_FOR_ATTR]                                    : "/catalogs/{catalogId}/attributes/{attributeId}/uoms",
	[AMAZE_API_NAMES.GET_USER]                                             : "/security/users/{userId}",
	[AMAZE_API_NAMES.GET_USER_GROUPS]                                      : "/security/userGroups",
	[AMAZE_API_NAMES.GET_USERS]                                            : "/security/users",
	[AMAZE_API_NAMES.GET_USERS_FOR_ROLE]                                   : "/security/roles/{roleId}/users",
	[AMAZE_API_NAMES.GET_VALIDATION_CONSTRAINTS_LIST]                      : "/catalogs/{catalogId}/validation/constraints",
	[AMAZE_API_NAMES.GET_VALIDATIONS_COUNT]                                : "/catalogs/{catalogId}/reports/validation/failures/skuCount",
	[AMAZE_API_NAMES.GETPHOTO_EDIT_BATCH_PROCESS]                          : "/daPhotoEditBatchProcess",
	[AMAZE_API_NAMES.GETPHOTO_EDIT_BATCH_PROCESS_COUNT]                    : "/daPhotoEditBatchProcess/count",
	[AMAZE_API_NAMES.IMPORT_TEMPLATEVALIDATE_NAME]                         : "/catalogs/{catalogId}/importTemplates/validateName",
	[AMAZE_API_NAMES.IS_ATTR_DUPLICATED]                                   : "/catalogs/{catalogId}/attributes/{attributeId}/isDuplicate?name]:{attributeTerm}",
	[AMAZE_API_NAMES.MOVE_PRODUCT_FAMILY]                                  : "/catalogs/{catalogId}/nodes/{nodeId}/productFamilies/{productFamilyId}/move",
	[AMAZE_API_NAMES.PASTE_SCHEMAS]                                        : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes-paste?sourceNode]:{sourceNode}&uom]:{uom}&lov]:{lov}&constraint]:{constraint}",
	[AMAZE_API_NAMES.PASTE_SCHEMAS_CHARACTERISTICS]                        : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes/{schemaAttributeId}/pasteFrom?uom]:{uom}&lov]:{lov}&constraint]:{constraint}",
	[AMAZE_API_NAMES.PATCH_ITERATION_SKU_ATTRIBUTE_VALUE]                  : "/catalogs/{catalogId}/domain/{domainId}/graingerTemplates/skuUpdate",
	[AMAZE_API_NAMES.GET_PF_RECOMMENDATION_STATUS]                         : "/catalogs/{catalogId}/nodes/{nodeId}/productFamily/recommendationStatus",
	[AMAZE_API_NAMES.PREVIEW_IMPORT_TEMPLATES]                             : "/catalogs/{catalogId}/importTemplates/preview",
	[AMAZE_API_NAMES.PROCESS_EXPORTS]                                      : "/catalogs/{catalogId}/exports/{exportId}",
	[AMAZE_API_NAMES.PROCESS_IMPORT]                                       : "/catalogs/{catalogId}/imports/{importId}/process",
	[AMAZE_API_NAMES.PROCESS_SAMPLE_OUTPUT_FOR_TEMPLATE]                   : "/daPhotoEditTemplates/{templateId}/process",
	[AMAZE_API_NAMES.RE_ASSIGN_REVIEW_REQUEST]                             : "/catalogs/{catalogId}/reviews/assign",
	[AMAZE_API_NAMES.REMOVE_ATTRIBUTE_GROUPS]                              : "/catalogs/{catalogId}/attributeGroups/{attributeGroupId}",
	[AMAZE_API_NAMES.REMOVE_ATTRIBUTE_IN_GROUPS]                           : "/catalogs/{catalogId}/attributeGroups/{attributeGroupId}/attributes-remove",
	[AMAZE_API_NAMES.REMOVE_PRIVILEGE_FROM_ROLE]                           : "/security/roles/{roleId}/privileges",
	[AMAZE_API_NAMES.REMOVE_ROLES_FROM_USER]                               : "/security/users/{userId}/roles",
	[AMAZE_API_NAMES.REMOVE_USERS_FROM_ROLE]                               : "/security/roles/{roleId}/users",
	[AMAZE_API_NAMES.REORDER_SCHEMA_ATTRIBUTES]                            : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes/{schemaAttributeId}/reorder",
	[AMAZE_API_NAMES.REPORT_FAVORITE]                                      : "/catalogs/{catalogId}/reports/{reportCode}/favorite",
	[AMAZE_API_NAMES.RESET_SCHEMA_DISPLAY_ORDER]                           : "/catalogs/{catalogId}/domain/{domainId}/resetDisplayOrder?reorderFlag]:RESET",
	[AMAZE_API_NAMES.ROLL_UP_SKU_ATTRIBUTES]                               : "/catalogs/{catalogId}/nodes/{nodeId}/productFamilies/{productFamilyId}/attributes/{attributeId}/rollAttributeValues?rollUp]:{rollUp}",
	[AMAZE_API_NAMES.SAVE_AS_IMPORT_TEMPLATE]                              : "/catalogs/{catalogId}/importTemplates/{existingTemplateId}/copyImportTemplate",
	[AMAZE_API_NAMES.SAVE_HYBRID_TEMPLATE_AS]                              : "/importHybridTemplates/{templateId}/saveImportHybridTemplateAs",
	[AMAZE_API_NAMES.SET_PRIVILEGES_FOR_ROLE]                              : "/security/roles/{roleId}/privileges",
	[AMAZE_API_NAMES.SET_PRIVILEGES_FOR_ROLE_FROM_CODES]                   : "/security/roles/{roleId}/privileges",
	[AMAZE_API_NAMES.DA_SUMMARY]                                           : "/digitalAssets/summary",
	[AMAZE_API_NAMES.TRIGGER_PHOTO_VISION_INFORMATION]                     : "/daPhotoBatchVisionInfoProcess",
	[AMAZE_API_NAMES.UOM_CONVERSION]                                       : "/catalogs/{catalogId}/attributes/{attributeId}/skuAttributeUomValues-convert",
	[AMAZE_API_NAMES.UPDATE_ATTRIBUTE_DIGITAL_ASSET_LINK]                  : "/catalogs/{catalogId}/attributeLinks/",
	[AMAZE_API_NAMES.UPDATE_ATTRIBUTE_GROUPS]                              : "/catalogs/{catalogId}/attributeGroups/{attributeGroupId}",
	[AMAZE_API_NAMES.UPDATE_EXPORTS]                                       : "/catalogs/{catalogId}/exports/{id}",
	[AMAZE_API_NAMES.UPDATE_FAILURE_FOR_UOMS_AND_LOVS]                     : "/catalogs/{catalogId}/reports/validation/failures/skusList",
	[AMAZE_API_NAMES.UPDATE_HYBRID_TEMPLATE]                               : "/importHybridTemplates/{templateId}",
	[AMAZE_API_NAMES.UPDATE_IMPORT_TEMPLATES]                              : "/catalogs/{catalogId}/importTemplates/{id}",
	[AMAZE_API_NAMES.UPDATE_IMPORTS]                                       : "/catalogs/{catalogId}/imports/{id}",
	[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU]                             : "/catalogs/{catalogId}/reviews/{reviewId}/skus/{skuId}",
	[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU_ATTRIBUTES]                  : "/catalogs/{catalogId}/reviews/{reviewId}/skuAttributes",
	[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU_DA_LINK]                     : "/catalogs/{catalogId}/reviews/{reviewId}/skuDigitalAssets",
	[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_TAXONOMY]                        : "/catalogs/{catalogId}/reviews/{reviewId}/skuMoves",
	[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_TAXONOMY_DA_LINK]                : "/catalogs/{catalogId}/reviews/{reviewId}/taxonomyDigitalAssets",
	[AMAZE_API_NAMES.UPDATE_REJECT_SCHEMA]                                 : "/catalogs/{catalogId}/reviews/{reviewId}/schema",
	[AMAZE_API_NAMES.UPDATE_REJECT_TAXONOMY_UPDATES]                       : "/catalogs/{catalogId}/reviews/{reviewId}/taxonomyUpdate",
	[AMAZE_API_NAMES.UPDATE_RELATED_SKUS]                                  : "/catalogs/{catalogId}/nodes/{nodeId}/skus/{skuId}/relatedSkus/{skuTaxoRelationId}",
	[AMAZE_API_NAMES.UPDATE_REVIEW_NOTES]                                  : "/catalogs/{catalogId}/reviews/{reviewId}/note",
	[AMAZE_API_NAMES.UPDATE_REVIEWS]                                       : "/catalogs/{catalogId}/reviews",
	[AMAZE_API_NAMES.UPDATE_ROLE]                                          : "/security/roles/{roleId}",
	[AMAZE_API_NAMES.UPDATE_SCHEMA_ATTRIBUTE_COMMENTS]                     : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes/{schemaAttributeId}/userComment-update",
	[AMAZE_API_NAMES.UPDATE_SCHEMA_ATTRIBUTE_NAVIGATION_ORDER]             : "/catalogs/{catalogId}/nodes/{nodeId}/schemaAttributes/{schemaAttributeId}/navigationOrder-update",
	[AMAZE_API_NAMES.UPDATE_SKU_DIGITAL_ASSET_LINK]                        : "/catalogs/{catalogId}/skuLinks",
	[AMAZE_API_NAMES.UPDATE_SKU_FROM_EXTERNAL_SOURCES]                     : "/catalogs/{catalogId}/skuAttributes",
	[AMAZE_API_NAMES.UPDATE_SKU_RELATIONSHIPS]                             : "/skuRelationships/{relationshipId}",
	[AMAZE_API_NAMES.UPDATE_SKU_VALUE_REPORT]                              : "/catalogs/{catalogId}/reports/{reportCode}/skus",
	[AMAZE_API_NAMES.UPDATE_TAXONOMY_DIGITAL_ASSET_LINK]                   : "/catalogs/{catalogId}/taxonomyLinks",
	[AMAZE_API_NAMES.UPDATE_USER]                                          : "/security/users/{userId}",
	[AMAZE_API_NAMES.UPLOAD_DIGITAL_CLOUD_STORAGE]                         : "/digitalAssets/{cloudStoreName}/drive",
	[AMAZE_API_NAMES.UPLOAD_DIGITAL_URL]                                   : "/digitalAssets/url",
	[AMAZE_API_NAMES.UPLOAD_DIGITAL_URL_FILE]                              : "/digitalAssets/urlFile",
	[AMAZE_API_NAMES.UPLOAD_DIGITAL_ZIP_FILE]                              : "/digitalAssets/zip",
	[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_ATTRIBUTES]                     : "/catalogs/{catalogId}/reports/validation/failures/by/attribute",
	[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_SCHEMA_CONSTRAINTS]             : "/catalogs/{catalogId}/reports/validation/failures/by/schemaConstraint",
	[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_SKU_LIST]                       : "/catalogs/{catalogId}/reports/validation/failures/skusList",
	[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_TOP_ATTRIBUTES]                 : "/catalogs/{catalogId}/reports/validation/failures/by/top/attribute",
	[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_TOP_NODES]                      : "/catalogs/{catalogId}/reports/validation/failures/by/top/node",
	[AMAZE_API_NAMES.GET_EXPORT_TEMPLATE_INFO]                             : "/catalogs/{catalogId}/exportTemplates/{templateId}",
	[AMAZE_API_NAMES.EXPORT_PRE_SIGNED_URL]                                : "/exportTemplateFile",
	[AMAZE_API_NAMES.EXPORT_TEMPLATE_FIELDS]                               : "/exportTemplateFields",
	[AMAZE_API_NAMES.EXPORT_TEMPLATES]                                     : "/catalogs/{catalogId}/exportTemplates",
	[AMAZE_API_NAMES.DELETE_EXPORT_TEMPLATE]                               : "/catalogs/{catalogId}/exportTemplates/{templateId}",
	[AMAZE_API_NAMES.UPDATE_EXPORT_TEMPLATE]                               : "/catalogs/{catalogId}/exportTemplates/{templateId}",
	[AMAZE_API_NAMES.GET_EXPORT_TEMPLATE_TYPES]                            : "/exportTemplateTypes",
	[AMAZE_API_NAMES.CHECK_EXPORT_TEMPLATE_NAME]                           : "/checkExportTemplateName?exportTemplateId]:{templateId}&exportTemplateName]:{templateName}",
	[AMAZE_API_NAMES.AMAZON_TEMPLATES]                                     : "/amazonTemplates",
	[AMAZE_API_NAMES.SINGLE_AMAZON_TEMPLATE]                               : "/amazonTemplates/{templateId}",
	[AMAZE_API_NAMES.DOWNLOAD_TEMPLATE_FILE]                               : "/amazonTemplates/{templateId}/amazonTemplateFile",
	[AMAZE_API_NAMES.AMAZON_FIELD_MAPPING_TYPES]                           : "/amazonFieldMappingTypes",
	[AMAZE_API_NAMES.GRAINGER_TEMPLATES]                                   : "/graingerTemplates",
	[AMAZE_API_NAMES.SINGLE_GRAINGER_TEMPLATE]                             : "/graingerTemplates/{templateId}",
	[AMAZE_API_NAMES.DOWNLOAD_GRAINGER_TEMPLATE_FILE]                      : "/graingerTemplates/{templateId}/graingerTemplateFile",
	[AMAZE_API_NAMES.GRAINGER_FIELD_MAPPING_TYPES]                         : "/graingerFieldMappingTypes",
	[AMAZE_API_NAMES.GRAINGER_LOVS]                                        : "/graingerTemplates/{templateId}/fields/{graingerTemplateFieldId}/values",
	[AMAZE_API_NAMES.GET_GRAINGER_TEMPLATE_SECTIONS]                       : "/graingerTemplates/{templateId}/sections",
	[AMAZE_API_NAMES.GET_UPLOADED_FILE_SECTIONS]                           : "/graingerTemplates/file/sections",
	[AMAZE_API_NAMES.REMOVE_UPLOADED_FILE]                                 : "/graingerTemplateFile",
	[AMAZE_API_NAMES.GET_AMAZE_PARAMS]                                     : "/parameters",
	[AMAZE_API_NAMES.GOOGLE_LOGIN]                                         : "/login?provider]:google",
	[AMAZE_API_NAMES.GET_AUTHENTICATION_TOKEN]                             : "/userToken",
	[AMAZE_API_NAMES.GET_USER_INFO]                                        : "/security/currentUser",
	[AMAZE_API_NAMES.LOGIN_BY_PASSWORD]                                    : "/loginByPassword",
	[AMAZE_API_NAMES.RESET_PASSWORD]                                       : "/security/resetPassword",
	[AMAZE_API_NAMES.FORGOT_PASSWORD]                                      : "/security/forgotPassword",
	[AMAZE_API_NAMES.LOGOUT]                                               : "/logout",
	[AMAZE_API_NAMES.GET_BRIDGE_CATALOGS]                                  : "/bridgeLink/bridgeCatalogs",
	[AMAZE_API_NAMES.CREATE_CATALOG_LINK]                                  : "/bridgeLink/domains/{domainId}",
	[AMAZE_API_NAMES.DELETE_CATALOG_LINK]                                  : "/bridgeLink/domains/{domainId}",
	[AMAZE_API_NAMES.GET_CATALOG_LINK]                                     : "/bridgeLink/domains/{domainId}",
	[AMAZE_API_NAMES.CREATE_CATALOG_SYNC_REQUEST]                          : "/bridgeLink/catalogSyncRequests",
	[AMAZE_API_NAMES.GET_CATALOG_SYNC_REQUESTS]                            : "/bridgeLink/catalogSyncRequests",
	[AMAZE_API_NAMES.GET_CATALOG_SYNC_STATUSES]                            : "/bridgeLink/catalogSyncStatuses",
	[AMAZE_API_NAMES.GET_CATALOG_SYNC_TYPES]                               : "/bridgeLink/catalogSyncTypes",
	[AMAZE_API_NAMES.GET_REAL_TIME_SYNC_LINKAGES]                          : "/bridgeLink/realTimeSyncLinkages",
	[AMAZE_API_NAMES.DELETE_REAL_TIME_LINKAGE]                             : "/bridgeLink/realTimeSyncLinkages/{linkageId}",
	[AMAZE_API_NAMES.CREATE_REAL_TIME_SYNC_LINKAGE]                        : "/bridgeLink/realTimeSyncLinkages",
	[AMAZE_API_NAMES.GET_PDP_TEMPLATES]                                    : "/skuPdpTemplates",
	[AMAZE_API_NAMES.CREATE_PDP_TEMPLATE]                                  : "/skuPdpTemplates",
	[AMAZE_API_NAMES.UPDATE_PDP_TEMPLATE]                                  : "/skuPdpTemplates/{skuPdpTemplateId}",
	[AMAZE_API_NAMES.DELETE_PDP_TEMPLATES]                                 : "/skuPdpTemplates/{skuPdpTemplateId}",
	[AMAZE_API_NAMES.DELETE_PDP_ELIGIBILTTY_TEMPLATES]                     : "/skuPdpTemplates/{skuPdpTemplateId}/eligibility",
	[AMAZE_API_NAMES.GET_TAXO_METATAGS]                                    : "/taxonomyMetaTags",
	[AMAZE_API_NAMES.CREATE_TAXO_METATAG]                                  : "/taxonomyMetaTags",
	[AMAZE_API_NAMES.UPDATE_TAXO_METATAG]                                  : "/taxonomyMetaTags",
	[AMAZE_API_NAMES.DELETE_TAXO_METATAG]                                  : "/taxonomyMetaTags/{tagId}",
	[AMAZE_API_NAMES.GET_TAXO_DETAILS_BY_METATAG]                          : "/taxonomyMetaTags/{tagId}/taxonomyPaths?count]:true",
	[AMAZE_API_NAMES.GET_TAXO_META_ATTR]                                   : "/taxonomyMetaAttributes",
	[AMAZE_API_NAMES.CREATE_TAXO_META_ATTR]                                : "/taxonomyMetaAttributes",
	[AMAZE_API_NAMES.UPDATE_TAXO_META_ATTR]                                : "/taxonomyMetaAttributes",
	[AMAZE_API_NAMES.GET_TAXO_DETAILS_BY_META_ATTR]                        : "/taxonomyMetaAttributes/{tagId}/taxonomyPaths?count]:true",
	[AMAZE_API_NAMES.DELETE_TAXO_META_ATTR]                                : "/taxonomyMetaAttributes/{tagId}",
	[AMAZE_API_NAMES.GET_BULK_ASSET_COUNT]                                 : "/digitalAssets/bulkDownload/count",
	[AMAZE_API_NAMES.SUBMIT_BULK_ASSET]                                    : "/digitalAssets/bulkDownload",
	[AMAZE_API_NAMES.GET_PRODUCT_SEARCH_CONFIGURATIONS]                    : "/skuSearchConditionFilters",
	[AMAZE_API_NAMES.GET_ADVANCE_SEARCH_SKU_RESULT]                        : "/catalogs/{catalogId}/conditions/{conditionId}",
	[AMAZE_API_NAMES.SAVE_ADVANCE_SEARCH_CONDITION]                        : "/skuSearchConditionFilters",
	[AMAZE_API_NAMES.GET_SAVED_CONDITIONS]                                 : "/conditions",
	[AMAZE_API_NAMES.GET_SAVED_CONDITION]                                  : "/conditions/{conditionId}",
	[AMAZE_API_NAMES.GET_SAVED_CONDITION_USAGES]                           : "/conditions/{conditionId}/linkages",
	[AMAZE_API_NAMES.GET_TERRAINS]                                         : "/customers/terrain",
	[AMAZE_API_NAMES.GET_TAXONOMY_RECOMMENDATIONS]                         : "/taxonomy/path/recommendation",
	[AMAZE_API_NAMES.GET_ATTRIBUTES_RECOMMENDATIONS]                       : "/attribute/detail/recommendation",
	[AMAZE_API_NAMES.SAVE_TAXONOMY_RECOMMENDATIONS]                        : "/catalogs/{catalogId}/nodes/tree",
	[AMAZE_API_NAMES.EDIT_ADVANCE_SEARCH_CONDITION]                        : "/conditions/{conditionId}",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_DETAILS]                                : "/catalogs/{catalogId}/attributes/details",
	[AMAZE_API_NAMES.GET_UOM_DETAILS]                                      : "/uoms/details",
	[AMAZE_API_NAMES.GET_CONFIDENCE_BUCKETS]                               : "/confidence/buckets",
	[AMAZE_API_NAMES.GET_CKB_SCHEMA_SUGGESTION]                            : "/catalogs/{catalogId}/ckb/attribute/name/recommendation",
	[AMAZE_API_NAMES.GET_CKB_ATTRIBUTES_WITH_AMAZE_MASTER_ATTRIBUTES]      : "/catalogs/{catalogId}/ckb/sku/attribute/recommendation",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_LOV_RECOMMENDATIONS]                    : "/attribute/detail/recommendation",
	[AMAZE_API_NAMES.GET_CONNECTORS_LIST]                                  : "/connectors",
	[AMAZE_API_NAMES.GET_CONNECTOR_CONFIGS]                                : "/connectors/{connectorId}/connectorConfigs",
	[AMAZE_API_NAMES.GET_CONNECTOR_CONFIG]                                 : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}",
	[AMAZE_API_NAMES.CREATE_CONNECTOR_CONFIG]                              : "/connectors/{connectorId}/connectorConfigs",
	[AMAZE_API_NAMES.UPDATE_CONNECTOR_CONFIG]                              : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}",
	[AMAZE_API_NAMES.DELETE_CONNECTOR_CONFIG]                              : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}",
	[AMAZE_API_NAMES.CHECK_CONNECTION]                                     : "/connectors/{connectorId}/connectorConfigs/checkConnection",
	[AMAZE_API_NAMES.GET_STORE_WEBSITES]                                   : "/connectors/{connectorId}/connectorConfigs/getStoreWebsites",
	[AMAZE_API_NAMES.GET_VENDOR_ATTRIBUTES]                                : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}/vendorAttributes",
	[AMAZE_API_NAMES.GET_ATTRIBUTE_MAPPINGS]                               : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}/catalogs/{catalogId}/attributeMappings",
	[AMAZE_API_NAMES.CREATE_ATTR_MAPPIGS]                                  : "/connectors/{connectorId}/connectorConfigs/{connectorConfigId}/catalogs/{catalogId}/attributeMappings",
	[AMAZE_API_NAMES.ADD_USER_NOTIFICATIONS]                               : "/catalogNotifications",
	[AMAZE_API_NAMES.DELET_USER_NOTIFICATIONS]                             : "/catalogNotifications/{userId}",
	[AMAZE_API_NAMES.GET_CURRENT_TOKEN]                                    : "/security/users/{userId}/apiToken/currentToken",
	[AMAZE_API_NAMES.GENERATE_TOKEN]                                       : "/security/users/{userId}/apiToken/tokens",
	[AMAZE_API_NAMES.DELETE_TOKEN]                                         : "/security/users/{userId}/apiToken",
	[AMAZE_API_NAMES.GET_FORMULAS]                                         : "/catalogs/{catalogId}/formulas",
	[AMAZE_API_NAMES.GET_FORMULA_SECTIONS]                                 : "/catalogs/{catalogId}/formulas/{formulaId}",
	[AMAZE_API_NAMES.CREATE_FORMULA]                                       : "/catalogs/{catalogId}/formulas",
	[AMAZE_API_NAMES.DELETE_FORMULA]                                       : "/catalogs/{catalogId}/formulas/{formulaId}/delete",
	[AMAZE_API_NAMES.EDIT_FORMULA]                                         : "/catalogs/{catalogId}/formulas/updateSections",
	[AMAZE_API_NAMES.ADD_FORMULA_TO_TAXONOMY]                              : "/catalogs/{catalogId}/formulas/{formulaId}/applyFormula",
	[AMAZE_API_NAMES.GET_SECTION_TYPES]                                    : "/catalogs/{catalogId}/formulas/sectionTypes",
	[AMAZE_API_NAMES.GET_SECTION_ARGUMENT_TYPES]                           : "/catalogs/{catalogId}/formulas/sectionArgumentTypes",
	[AMAZE_API_NAMES.GET_SECTION_INPUT_VALUES]                             : "/catalogs/{catalogId}/formulas/sectionInputValues",
	[AMAZE_API_NAMES.CLEAR_FORMULA]                                        : "/catalogs/{catalogId}/formulas/clearTaxonomyFormula",
	[AMAZE_API_NAMES.MANAGE_TAXONOMY_FORMULA]                              : "/catalogs/{catalogId}/formulas/{formulaId}/manageTaxonomyFormula",
	[AMAZE_API_NAMES.ENTITIES_ATTACHED_TO_FORMULA]                         : "/catalogs/{catalogId}/formulas/{formulaId}/entitiesToRemoveFormula",
	[AMAZE_API_NAMES.CHECK_EXPRESSION]                                     : "/checkExpression",
	[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES_LOCK_INFO]                         : "/catalogs/{catalogId}/skuAttributes/lock",
	[AMAZE_API_NAMES.GET_SKU_ATTR_VALUE_STAGING_INFO]                      : "/catalogs/{catalogId}/skuAttributes/{skuAttributeId}/stagingValues",
	[AMAZE_API_NAMES.APPROVE_SKU_ATTR_VALUE_STAGING_VALUES]                : "/catalogs/{catalogId}/skuAttributes/{skuAttributeId}/approveStagingValues",
	[AMAZE_API_NAMES.CREATE_ATTRIBUTE_LOCK]                                : "/catalogs/{catalogId}/skuAttributes/lock",
	[AMAZE_API_NAMES.GET_LOCKED_ATTRIBUTES]                                : "/catalogs/{catalogId}/lockAttributes",
	[AMAZE_API_NAMES.UNLOCK_ATTRIBUTE_LOCK]                                : "/catalogs/{catalogId}/skuAttributes/unlock",
	[AMAZE_API_NAMES.GENERATE_OTP]                                         : "/catalogs/{catalogId}/domain/{domainId}/deletionRequest",
	[AMAZE_API_NAMES.GET_CUSTOMER_NAME]                                    : "/customers/name",
	[AMAZE_API_NAMES.GET_ALL_WIDGETS]                                      : "/userWidgets/{userId}",
	[AMAZE_API_NAMES.GET_WIDGET_DATA]                                      : "/catalogs/{catalogId}/domain/{domainId}/userWidgets/data",
	[AMAZE_API_NAMES.GET_WIDGET_RANGE]                                     : "/catalogs/{catalogId}/domain/{domainId}/userWidgets/range?widgetCode]:S2",
	[AMAZE_API_NAMES.ENABLE_DISABLE_WIDGET]                                : "/userWidgets",
	[AMAZE_API_NAMES.REORDER_WIDGETS]                                      : "/userWidgets",
	[AMAZE_API_NAMES.RESET_WIDGET_ORDER]                                   : "/userWidgets/{userId}",
	[AMAZE_API_NAMES.GET_PRODUCT]                                          : "/catalogs/{catalogId}/skus",
	[AMAZE_API_NAMES.GET_PRODUCT_LIST]                                     : "/catalogs/{catalogId}/skus/productListing",
	[AMAZE_API_NAMES.GET_LEAN_ATTRIBUTES]                                  : "/catalogs/{catalogId}/leanAttributes",
	[AMAZE_API_NAMES.GET_SKU_VARIANTS]                                     : "/catalogs/{catalogId}/skusVariants",
	[AMAZE_API_NAMES.GET_DATA_QUALITY_PROBLEMS]                            : "/catalogs/{catalogId}/skus/{skuId}/dataQualityScoreProlems",
	[AMAZE_API_NAMES.GET_SYNDICATION_INFO]                                 : "/catalogs/{catalogId}/skus/{skuId}/syndicationInfo",
	[AMAZE_API_NAMES.GET_SYNDICATION_VALIDATION_FAILURES]                  : "/catalogs/{catalogId}/skus/{skuId}/syndicationValidationFailures",
	[AMAZE_API_NAMES.GET_SYNDICATION_UN_MAPPED_ATTRIBUTES]                 : "/catalogs/{catalogId}/skus/{skuId}/syndicationUnmappedAttributes",
	[AMAZE_API_NAMES.GET_SYNDICATION_FROM_CONSOLIDATION]                   : "/catalogs/{catalogId}/skus/{skuId}/syndicationFromConsolidation",
	[AMAZE_API_NAMES.GET_SYNDICATION_ATTRIBUTE_MAPPING_DETAILS]            : "/catalogs/{catalogId}/skus/{skuId}/syndicationAttributeMappingDetails",
	[AMAZE_API_NAMES.GET_ATTR_CATEGORIES]                                  : "/catalogs/{catalogId}/skus/{skuId}/skuAttributes360view",
	[AMAZE_API_NAMES.GET_MARKETING_RECOMMENDATION]                         : "/catalogs/{catalogId}/skus/{skuId}/marketing/recommendation",
	[AMAZE_API_NAMES.GET_ASSORTMENTS]                                      : "/catalogs/{catalogId}/assortments",
	[AMAZE_API_NAMES.ADD_ASSORTMENT]                                       : "/catalogs/{catalogId}/assortments",
	[AMAZE_API_NAMES.EDIT_ASSORTMENT]                                      : "/catalogs/{catalogId}/assortments",
	[AMAZE_API_NAMES.DELETE_ASSORTMENT]                                    : "/catalogs/{catalogId}/assortments/{assortmentId}",
	[AMAZE_API_NAMES.ADD_SKUS_TO_ASSORTMENT]                               : "/catalogs/{catalogId}/populateSkuAssortments",
	[AMAZE_API_NAMES.REMOVE_SKUS_FROM_ASSORTMENT]                          : "/catalogs/{catalogId}/deleteSkuAssortments",

	// Channels related API urls
	[AMAZE_API_NAMES.GET_BRIDGE_CHANNELS]                                  : "/bridge/projects",
	[AMAZE_API_NAMES.CREATE_CHANNEL]                                       : "/bridge/projects",
	[AMAZE_API_NAMES.DELETE_CHANNEL]                                       : "/bridge/projects/{projectId}",
	[AMAZE_API_NAMES.GET_BRIDGE_CHANNEL]                                   : "/bridge/projects/{projectId}",
	[AMAZE_API_NAMES.GET_BRIDGE_CHANNEL_FOR_CATALOG_CREATION]              : "/bridge/catalogs",
	[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_NODES]                             : "/bridge/projects/{projectId}/catalogs/{catalogId}/nodes/amaze?depth]:2",
	[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_CHILD_NODES]                       : "/bridge/catalogs/{catalogId}/nodes/{nodeId}/amaze?depth]:2",
	[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_NODES_SEARCH]                      : "/bridge/projects/{projectId}/catalogs/{catalogId}/nodes/amaze?partialNameOrId]:{nameOrId}",
	[AMAZE_API_NAMES.CHANGE_CHANNEL_STATE]                                 : "/bridge/projectss/{projectId}?fields={state}",
	[AMAZE_API_NAMES.BUILD_CHANNEL]                                        : "/bridge/projects/{projectId}/applyMappers",
	[AMAZE_API_NAMES.VALIDATE_MAP]                                         : "/bridge/mapsBackups/project/{projectId}/validateBackupByName?backupName={backupName}",
	[AMAZE_API_NAMES.CREATE_NEW_MAP]                                       : "/bridge/downlodRequest/createNew?timezone={timezone}&backupName={backupName}",
	[AMAZE_API_NAMES.GET_BACKUP_MAPS]                                      : "/bridge/mapsBackups/count",
	[AMAZE_API_NAMES.GET_BACKUP_MAPS_COUNT]                                : "/bridge/mapsBackups",
	[AMAZE_API_NAMES.RESTORE_BACKUP_MAPS]                                  : "/bridge/downlodRequest/createNew?timezone={timezone}&mapsBackupId={mapsBackupId}&restoreMapTo={restoreMapTo}&fromCatalog={fromCatalog}",
	[AMAZE_API_NAMES.GET_AMAZE_CATALOG_DETAILS_FROM_BRIDGE_CATALOG]        : "/bridge/{bridgeCatalogId}/getAmazeLinkedCatalog",
	[AMAZE_API_NAMES.GET_NODE_MAPS]                                        : "/bridge/projects/{projectId}/catalogs/{catalogId}/nodes/{nodeId}/nodeMaps",
	[AMAZE_API_NAMES.GET_PRE_TRANSFORM_SKUS]                               : "/bridge/projects/{projectId}/catalogs/{catalogId}/nodes/{nodeId}/nodeMaps/{nodeMapId}/skus",
	[AMAZE_API_NAMES.GET_TRANSFORMED_SKUS]                                 : "/bridge/projects/{projectId}/catalogs/{catalogId}/nodes/{nodeId}/nodeMaps/{mapperId}/transform"
}

export enum AMAZE_SOCKET_URLS {
	AMAZE    = "/amazeevents",
	TAXONOMY_EVENTS = "/taxonomyevents"
}
