import { IAmazeApi, API_METHOD } from "@app/core/backend/api.types";
import { AMAZE_API_NAMES } from "@app/core/backend/api.constants";
import { AMAZE_API_URLS } from "@app/core/backend/api.paths";

const APIS : Record<string, IAmazeApi> = {};

APIS[AMAZE_API_NAMES.GET_ENTITY_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ENTITY_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_BASIC_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_BASIC_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_DOMAIN_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_DOMAIN_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_CATALOG] = {
    METHOD: API_METHOD.POST,
    URL: AMAZE_API_URLS.CREATE_CATALOG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_CATALOG] = {
    METHOD: API_METHOD.DELETE,
    URL: AMAZE_API_URLS.DELETE_CATALOG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ALL_CATALOGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ALL_CATALOGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DOMAINS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DOMAINS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_DOMAIN] = {
    METHOD: API_METHOD.POST,
    URL: AMAZE_API_URLS.ADD_DOMAIN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_DOMAIN] = {
    METHOD: API_METHOD.PATCH,
    URL: AMAZE_API_URLS.UPDATE_DOMAIN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_DOMAIN] = {
    METHOD: API_METHOD.DELETE,
    URL: AMAZE_API_URLS.DELETE_DOMAIN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_STYLE_GUIDE_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_STYLE_GUIDE_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_STYLE_GUIDE_REPORT_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_STYLE_GUIDE_REPORT_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_STYLE_GUIDE_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_STYLE_GUIDE_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_STYLE_GUIDE_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_STYLE_GUIDE_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PERFORM_CHECK_STYLE_GUIDE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PERFORM_CHECK_STYLE_GUIDE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CATALOG_GLOBAL_SEARCH] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CATALOG_GLOBAL_SEARCH,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SKU_GLOBAL_SEARCH] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SKU_GLOBAL_SEARCH,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_CHILD_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_CHILD_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODES_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODES_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODES_IN_ORDER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODES_IN_ORDER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODES_SEARCH] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODES_SEARCH,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODES_SEARCH_HIERARCHY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODES_SEARCH_HIERARCHY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_NODE_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_NODE_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.MOVE_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.MOVE_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REORDER_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REORDER_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.COPY_TAXONOMY_STRUCTURE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.COPY_TAXONOMY_STRUCTURE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKUS_BY_NODE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKUS_BY_NODE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.MOVE_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.MOVE_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.MIRROR_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.MIRROR_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_MIRROR_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_MIRROR_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CROSS_LIST_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CROSS_LIST_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CROSSLIST_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CROSSLIST_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_CROSSLIST_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_CROSSLIST_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_CROSSLIST_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_CROSSLIST_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_SKU_CROSS_LISTING] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_SKU_CROSS_LISTING,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_IDS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_IDS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_RELATIONSHIPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_RELATIONSHIPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_SKU_RELATIONSHIPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_SKU_RELATIONSHIPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SKU_RELATIONSHIPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SKU_RELATIONSHIPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SKU_RELATIONSHIPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SKU_RELATIONSHIPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_RELATED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_RELATED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_RELATED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_RELATED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_RELATED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_RELATED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_RELATED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_RELATED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TARGET_UOM] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TARGET_UOM,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CONVERSION_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CONVERSION_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SCHEMA_ATTR_ON_MULTIPLE_NODE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SCHEMA_ATTR_ON_MULTIPLE_NODE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UOM_CONVERSION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UOM_CONVERSION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXTERNAL_SOURCES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXTERNAL_SOURCES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_SKU_FROM_EXTERNAL_SOURCES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_SKU_FROM_EXTERNAL_SOURCES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SKU_FROM_EXTERNAL_SOURCES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SKU_FROM_EXTERNAL_SOURCES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SKU_FROM_EXTERNAL_SOURCES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SKU_FROM_EXTERNAL_SOURCES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.COPY_SKU_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.COPY_SKU_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_STATIC_HTML] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_STATIC_HTML,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXTERNAL_SOURCES_AUDIT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXTERNAL_SOURCES_AUDIT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_VALIDATION_FAILURES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES_FOR_TAXONOMY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_VALIDATION_FAILURES_FOR_TAXONOMY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_VALIDATION_FAILURES_SUMMARY_FOR_TAXONOMY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_VALIDATION_FAILURES_SUMMARY_FOR_TAXONOMY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES_FOR_FILTERING] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_ATTRIBUTES_FOR_FILTERING,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SCHEMA_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SCHEMA_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_COPIED_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_COPIED_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PASTE_SCHEMAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PASTE_SCHEMAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PASTE_SCHEMAS_CHARACTERISTICS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PASTE_SCHEMAS_CHARACTERISTICS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REORDER_SCHEMA_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REORDER_SCHEMA_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SCHEMA_ATTRIBUTE_COMMENTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SCHEMA_ATTRIBUTE_COMMENTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SCHEMA_ATTRIBUTE_NAVIGATION_ORDER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SCHEMA_ATTRIBUTE_NAVIGATION_ORDER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.RESET_SCHEMA_DISPLAY_ORDER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.RESET_SCHEMA_DISPLAY_ORDER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_FAMILIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_FAMILIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_FAMILY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_FAMILY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CHILD_PRODUCT_FAMILIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CHILD_PRODUCT_FAMILIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_FAMILIES_BY_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_FAMILIES_BY_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_FAMILY_TREE_HIERARCHY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_FAMILY_TREE_HIERARCHY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ATTACH_SKU_TO_PRODUCT_FAMILIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ATTACH_SKU_TO_PRODUCT_FAMILIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DETACH_SKU_TO_PRODUCT_FAMILIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DETACH_SKU_TO_PRODUCT_FAMILIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ROLL_UP_SKU_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ROLL_UP_SKU_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.MOVE_PRODUCT_FAMILY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.MOVE_PRODUCT_FAMILY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_PRODUCT_FAMILY_TITLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_PRODUCT_FAMILY_TITLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXECUTE_PF_RECOMMENDATION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXECUTE_PF_RECOMMENDATION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PF_RECOMMENDATION_STATUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PF_RECOMMENDATION_STATUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CASCADE_VALUE_TO_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CASCADE_VALUE_TO_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ATTRIBUTES_SEARCH] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ATTRIBUTES_SEARCH,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.IS_ATTR_DUPLICATED] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.IS_ATTR_DUPLICATED,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_ATTRIBUTE_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_ATTRIBUTE_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_ATTRIBUTE_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_ATTRIBUTE_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_ATTRIBUTE_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_ATTRIBUTE_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTES_IN_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTES_IN_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ATTRIBUTE_IN_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ATTRIBUTE_IN_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_ATTRIBUTE_IN_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_ATTRIBUTE_IN_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_METATAG_RELEVANCE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_METATAG_RELEVANCE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ATTRIBUTE_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ATTRIBUTE_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_ATTRIBUTE_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_ATTRIBUTE_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ATTRIBUTE_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ATTRIBUTE_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_META_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_META_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ATTRIBUTE_META_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ATTRIBUTE_META_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_ATTRIBUTE_META_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_ATTRIBUTE_META_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ATTRIBUTE_META_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ATTRIBUTE_META_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UOMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UOMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_UOMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_UOMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_UOMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_UOMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_UOM] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_UOM,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UOMS_CATEGORIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UOMS_CATEGORIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRE_SIGNED_URL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRE_SIGNED_URL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DIGITAL_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DIGITAL_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DIGITAL_ASSET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DIGITAL_ASSET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_DIGITAL_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_DIGITAL_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_DIGITAL_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_DIGITAL_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPLOAD_DIGITAL_URL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPLOAD_DIGITAL_URL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPLOAD_DIGITAL_URL_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPLOAD_DIGITAL_URL_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPLOAD_DIGITAL_ZIP_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPLOAD_DIGITAL_ZIP_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPLOAD_DIGITAL_CLOUD_STORAGE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPLOAD_DIGITAL_CLOUD_STORAGE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ASSET_TAGS_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ASSET_TAGS_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_ASSET_MANIFEST_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_ASSET_MANIFEST_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.BULK_UPDATE_DA_METADATA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.BULK_UPDATE_DA_METADATA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DA_COUNTS_FOR_ADVANCED_FILTER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DA_COUNTS_FOR_ADVANCED_FILTER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DA_METATAGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DA_METATAGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DA_META_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DA_META_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ATTRIBUTES_FOR_DIGITAL_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ATTRIBUTES_FOR_DIGITAL_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DA_SUMMARY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DA_SUMMARY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.TRIGGER_PHOTO_VISION_INFORMATION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.TRIGGER_PHOTO_VISION_INFORMATION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ASSET_VISION_INFO_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ASSET_VISION_INFO_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ASSET_VISION_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ASSET_VISION_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKUS_RECOMMENDED_DA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKUS_RECOMMENDED_DA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DIGITAL_ASSET_FOR_IMPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DIGITAL_ASSET_FOR_IMPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DIGITAL_ASSET_FOR_IMPORT_DETAISL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DIGITAL_ASSET_FOR_IMPORT_DETAISL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_IMPORT_ERROR_LOG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_IMPORT_ERROR_LOG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UNIQUE_ERROR_MESSAGES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UNIQUE_ERROR_MESSAGES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DA_META_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DA_META_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DA_META_TAGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DA_META_TAGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_META_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_META_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_META_TAGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_META_TAGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_ID] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_ID,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_TAXONOMY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_TAXONOMY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXONOMY_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_TAXONOMY_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_TAXONOMY_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_TAXONOMY_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_TAXONOMY_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_TAXONOMY_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_TAXONOMY_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXONOMY_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXONOMY_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_ID] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_DIGITAL_ASSET_LINKS_BY_ID,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_SKU] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_DIGITAL_ASSET_LINKS_BY_SKU,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_SKU_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_SKU_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SKU_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SKU_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SKU_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SKU_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ID] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ID,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ATTRIBUTE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_ATTRIBUTE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_DIGITAL_ASSET_LINKS_BY_DIGITAL_ASSET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_ATTRIBUTE_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_ATTRIBUTE_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_ATTRIBUTE_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_ATTRIBUTE_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ATTRIBUTE_DIGITAL_ASSET_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ATTRIBUTE_DIGITAL_ASSET_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_META_ATTRIBUTE_DIGITAL_ASSET_LINKS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PHOTO_EDIT_TEMPLATES_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PHOTO_EDIT_TEMPLATES_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PHOTO_EDIT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PHOTO_EDIT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_PHOTO_EDIT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_PHOTO_EDIT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_PHOTO_EDIT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_PHOTO_EDIT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_PHOTO_EDIT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_PHOTO_EDIT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GETPHOTO_EDIT_BATCH_PROCESS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GETPHOTO_EDIT_BATCH_PROCESS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GETPHOTO_EDIT_BATCH_PROCESS_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GETPHOTO_EDIT_BATCH_PROCESS_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_BATCH_PROCESS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_BATCH_PROCESS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PROCESS_SAMPLE_OUTPUT_FOR_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PROCESS_SAMPLE_OUTPUT_FOR_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BATCH_PROCESS_PROCESSED_ASSETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BATCH_PROCESS_PROCESSED_ASSETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_USERS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_USERS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ROLES_FOR_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ROLES_FOR_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ROLES_TO_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ROLES_TO_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_ROLES_FROM_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_ROLES_FROM_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRIVILEGES_FOR_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRIVILEGES_FOR_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRIVILEGE_CODES_FOR_USER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRIVILEGE_CODES_FOR_USER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ROLES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ROLES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_USERS_FOR_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_USERS_FOR_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_USERS_TO_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_USERS_TO_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_USERS_FROM_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_USERS_FROM_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ASSIGN_USERS_TO_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ASSIGN_USERS_TO_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ASSIGN_ROLES_TO_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ASSIGN_ROLES_TO_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_USER_GROUPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_USER_GROUPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_GLOBAL_PRIVILEGES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_GLOBAL_PRIVILEGES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRIVILEGES_FOR_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRIVILEGES_FOR_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRIVILEGE_CODES_FOR_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRIVILEGE_CODES_FOR_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_PRIVILEGE_TO_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_PRIVILEGE_TO_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_PRIVILEGE_FROM_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_PRIVILEGE_FROM_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SET_PRIVILEGES_FOR_ROLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SET_PRIVILEGES_FOR_ROLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SET_PRIVILEGES_FOR_ROLE_FROM_CODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SET_PRIVILEGES_FOR_ROLE_FROM_CODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CATALOG_DOMAIN_REVIEW_PRIVILEGES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CATALOG_DOMAIN_REVIEW_PRIVILEGES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEWS_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEWS_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REVIEWS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REVIEWS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW_HISTORY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW_HISTORY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW_COUNTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW_COUNTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REVIEW_NOTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REVIEW_NOTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.RE_ASSIGN_REVIEW_REQUEST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.RE_ASSIGN_REVIEW_REQUEST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHECK_PENDING_TAXONOMY_REVIEW] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHECK_PENDING_TAXONOMY_REVIEW,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW_RESTRICTIONS_MATRIX] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW_RESTRICTIONS_MATRIX,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW_STATUSES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW_STATUSES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REVIEW_ACTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REVIEW_ACTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_RESTRICTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_RESTRICTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_REVIEW_SKU_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU_DA_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_REVIEW_SKU_DA_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_TAXONOMY_DA_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_REVIEW_TAXONOMY_DA_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_TAXONOMY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_REVIEW_TAXONOMY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_REVIEW_SKU] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_REVIEW_SKU,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_TAXONOMY_UPDATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_TAXONOMY_UPDATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_REJECT_SCHEMA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_REJECT_SCHEMA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ALL_REPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ALL_REPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXECUTION_HISTORY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXECUTION_HISTORY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REPORT_FAVORITE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REPORT_FAVORITE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXECUTE_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXECUTE_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FETCH_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FETCH_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FETCH_P_7_DRILLDOWN_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FETCH_P_7_DRILLDOWN_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FETCH_P_1_DRILLDOWN_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FETCH_P_1_DRILLDOWN_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_LOVS_FOR_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_LOVS_FOR_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UOMS_FOR_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UOMS_FOR_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_SKU_VALUE_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_SKU_VALUE_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_REPORT_T_1] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_REPORT_T_1,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_P_12] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_P_12,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_REPORT_S_10_LOVS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_REPORT_S_10_LOVS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_REPORT_S_10_UOMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_REPORT_S_10_UOMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FIX_REPORT_S_10_CONSTRAINTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FIX_REPORT_S_10_CONSTRAINTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_NOTE_TO_REPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_NOTE_TO_REPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHECK_LOV_SUGGESTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHECK_LOV_SUGGESTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_VALIDATION_CONSTRAINTS_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_VALIDATION_CONSTRAINTS_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_SCHEMA_CONSTRAINTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATION_FAILURE_BY_SCHEMA_CONSTRAINTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATION_FAILURE_BY_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_TOP_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATION_FAILURE_BY_TOP_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_TOP_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATION_FAILURE_BY_TOP_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATION_FAILURE_BY_SKU_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATION_FAILURE_BY_SKU_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_FAILURE_FOR_UOMS_AND_LOVS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_FAILURE_FOR_UOMS_AND_LOVS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_LOV_SUGGESTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_LOV_SUGGESTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_VALIDATIONS_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_VALIDATIONS_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SINGLE_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SINGLE_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PREVIEW_IMPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PREVIEW_IMPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.IMPORT_TEMPLATEVALIDATE_NAME] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.IMPORT_TEMPLATEVALIDATE_NAME,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SAVE_AS_IMPORT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SAVE_AS_IMPORT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_HYBRID_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_HYBRID_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_HYBRID_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_HYBRID_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_HYBRID_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_HYBRID_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SAVE_HYBRID_TEMPLATE_AS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SAVE_HYBRID_TEMPLATE_AS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_HYBRID_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_HYBRID_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_IMPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_IMPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_IMPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_IMPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_IMPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_IMPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_IMPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_IMPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_IMPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_IMPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PROCESS_IMPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PROCESS_IMPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_IMPORT_FILE_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_IMPORT_FILE_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_IMPORT_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_IMPORT_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_EXPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_EXPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_EXPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_EXPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_EXPORT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_EXPORT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT_FILE_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT_FILE_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_EXPORT_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_EXPORT_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_EXPORT_SAMPLE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_EXPORT_SAMPLE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PROCESS_EXPORTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PROCESS_EXPORTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SEARCHED_CONDITION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SEARCHED_CONDITION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_LATEST_EXPORT_DATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_LATEST_EXPORT_DATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_GRAINGER_SKU_UPDATE_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_GRAINGER_SKU_UPDATE_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_GRAINGER_ITERATION_FAILED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_GRAINGER_ITERATION_FAILED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.PATCH_ITERATION_SKU_ATTRIBUTE_VALUE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.PATCH_ITERATION_SKU_ATTRIBUTE_VALUE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ITERATION_FAILURE_DESCRIPTION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ITERATION_FAILURE_DESCRIPTION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BME_CAT_VERSIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BME_CAT_VERSIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT_READINESS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT_READINESS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT_TEMPLATE_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT_TEMPLATE_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXPORT_PRE_SIGNED_URL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXPORT_PRE_SIGNED_URL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXPORT_TEMPLATE_FIELDS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXPORT_TEMPLATE_FIELDS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EXPORT_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EXPORT_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_EXPORT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_EXPORT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_EXPORT_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_EXPORT_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_EXPORT_TEMPLATE_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_EXPORT_TEMPLATE_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHECK_EXPORT_TEMPLATE_NAME] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHECK_EXPORT_TEMPLATE_NAME,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.AMAZON_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.AMAZON_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SINGLE_AMAZON_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SINGLE_AMAZON_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_TEMPLATE_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_TEMPLATE_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.AMAZON_FIELD_MAPPING_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.AMAZON_FIELD_MAPPING_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GRAINGER_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GRAINGER_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SINGLE_GRAINGER_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SINGLE_GRAINGER_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DOWNLOAD_GRAINGER_TEMPLATE_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DOWNLOAD_GRAINGER_TEMPLATE_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GRAINGER_FIELD_MAPPING_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GRAINGER_FIELD_MAPPING_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GRAINGER_LOVS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GRAINGER_LOVS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_GRAINGER_TEMPLATE_SECTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_GRAINGER_TEMPLATE_SECTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UPLOADED_FILE_SECTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UPLOADED_FILE_SECTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_UPLOADED_FILE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_UPLOADED_FILE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_AMAZE_PARAMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_AMAZE_PARAMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GOOGLE_LOGIN] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GOOGLE_LOGIN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_AUTHENTICATION_TOKEN] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_AUTHENTICATION_TOKEN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_USER_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_USER_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.LOGIN_BY_PASSWORD] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.LOGIN_BY_PASSWORD,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.RESET_PASSWORD] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.RESET_PASSWORD,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.FORGOT_PASSWORD] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.FORGOT_PASSWORD,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.LOGOUT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.LOGOUT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CATALOGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CATALOGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_CATALOG_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_CATALOG_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_CATALOG_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_CATALOG_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_LINK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_LINK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_CATALOG_SYNC_REQUEST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_CATALOG_SYNC_REQUEST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_SYNC_REQUESTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_SYNC_REQUESTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_SYNC_STATUSES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_SYNC_STATUSES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CATALOG_SYNC_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CATALOG_SYNC_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_REAL_TIME_SYNC_LINKAGES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_REAL_TIME_SYNC_LINKAGES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_REAL_TIME_LINKAGE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_REAL_TIME_LINKAGE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_REAL_TIME_SYNC_LINKAGE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_REAL_TIME_SYNC_LINKAGE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PDP_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PDP_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_PDP_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_PDP_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_PDP_TEMPLATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_PDP_TEMPLATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_PDP_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_PDP_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_PDP_ELIGIBILTTY_TEMPLATES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_PDP_ELIGIBILTTY_TEMPLATES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXO_METATAGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXO_METATAGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_TAXO_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_TAXO_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_TAXO_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_TAXO_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_TAXO_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_TAXO_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXO_DETAILS_BY_METATAG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXO_DETAILS_BY_METATAG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXO_META_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXO_META_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_TAXO_META_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_TAXO_META_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_TAXO_META_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_TAXO_META_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXO_DETAILS_BY_META_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXO_DETAILS_BY_META_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_TAXO_META_ATTR] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_TAXO_META_ATTR,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BULK_ASSET_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BULK_ASSET_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SUBMIT_BULK_ASSET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SUBMIT_BULK_ASSET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_SEARCH_CONFIGURATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_SEARCH_CONFIGURATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ADVANCE_SEARCH_SKU_RESULT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ADVANCE_SEARCH_SKU_RESULT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SAVE_ADVANCE_SEARCH_CONDITION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SAVE_ADVANCE_SEARCH_CONDITION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SAVED_CONDITIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SAVED_CONDITIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SAVED_CONDITION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SAVED_CONDITION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SAVED_CONDITION_USAGES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SAVED_CONDITION_USAGES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TERRAINS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TERRAINS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TAXONOMY_RECOMMENDATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TAXONOMY_RECOMMENDATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTES_RECOMMENDATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTES_RECOMMENDATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.SAVE_TAXONOMY_RECOMMENDATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.SAVE_TAXONOMY_RECOMMENDATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_ADVANCE_SEARCH_CONDITION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_ADVANCE_SEARCH_CONDITION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_UOM_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_UOM_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CONFIDENCE_BUCKETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CONFIDENCE_BUCKETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CKB_SCHEMA_SUGGESTION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CKB_SCHEMA_SUGGESTION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CKB_ATTRIBUTES_WITH_AMAZE_MASTER_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CKB_ATTRIBUTES_WITH_AMAZE_MASTER_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_LOV_RECOMMENDATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_LOV_RECOMMENDATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CONNECTORS_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CONNECTORS_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CONNECTOR_CONFIGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CONNECTOR_CONFIGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CONNECTOR_CONFIG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CONNECTOR_CONFIG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_CONNECTOR_CONFIG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_CONNECTOR_CONFIG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UPDATE_CONNECTOR_CONFIG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UPDATE_CONNECTOR_CONFIG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_CONNECTOR_CONFIG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_CONNECTOR_CONFIG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHECK_CONNECTION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHECK_CONNECTION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_STORE_WEBSITES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_STORE_WEBSITES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_VENDOR_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_VENDOR_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTRIBUTE_MAPPINGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTRIBUTE_MAPPINGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_ATTR_MAPPIGS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_ATTR_MAPPIGS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_USER_NOTIFICATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_USER_NOTIFICATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELET_USER_NOTIFICATIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELET_USER_NOTIFICATIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CURRENT_TOKEN] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CURRENT_TOKEN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GENERATE_TOKEN] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GENERATE_TOKEN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_TOKEN] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_TOKEN,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_FORMULAS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_FORMULAS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_FORMULA_SECTIONS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_FORMULA_SECTIONS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_FORMULA_TO_TAXONOMY] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_FORMULA_TO_TAXONOMY,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SECTION_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SECTION_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SECTION_ARGUMENT_TYPES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SECTION_ARGUMENT_TYPES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SECTION_INPUT_VALUES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SECTION_INPUT_VALUES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CLEAR_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CLEAR_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.MANAGE_TAXONOMY_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.MANAGE_TAXONOMY_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ENTITIES_ATTACHED_TO_FORMULA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ENTITIES_ATTACHED_TO_FORMULA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHECK_EXPRESSION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHECK_EXPRESSION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_ATTRIBUTES_LOCK_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_ATTRIBUTES_LOCK_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_ATTR_VALUE_STAGING_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_ATTR_VALUE_STAGING_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.APPROVE_SKU_ATTR_VALUE_STAGING_VALUES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.APPROVE_SKU_ATTR_VALUE_STAGING_VALUES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_ATTRIBUTE_LOCK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_ATTRIBUTE_LOCK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_LOCKED_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_LOCKED_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.UNLOCK_ATTRIBUTE_LOCK] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.UNLOCK_ATTRIBUTE_LOCK,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GENERATE_OTP] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GENERATE_OTP,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_CUSTOMER_NAME] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_CUSTOMER_NAME,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ALL_WIDGETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ALL_WIDGETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_WIDGET_DATA] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_WIDGET_DATA,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_WIDGET_RANGE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_WIDGET_RANGE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ENABLE_DISABLE_WIDGET] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ENABLE_DISABLE_WIDGET,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REORDER_WIDGETS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REORDER_WIDGETS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.RESET_WIDGET_ORDER] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.RESET_WIDGET_ORDER,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRODUCT_LIST] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRODUCT_LIST,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_LEAN_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_LEAN_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SKU_VARIANTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SKU_VARIANTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_DATA_QUALITY_PROBLEMS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_DATA_QUALITY_PROBLEMS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SYNDICATION_INFO] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SYNDICATION_INFO,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SYNDICATION_VALIDATION_FAILURES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SYNDICATION_VALIDATION_FAILURES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SYNDICATION_UN_MAPPED_ATTRIBUTES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SYNDICATION_UN_MAPPED_ATTRIBUTES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SYNDICATION_FROM_CONSOLIDATION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SYNDICATION_FROM_CONSOLIDATION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_SYNDICATION_ATTRIBUTE_MAPPING_DETAILS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_SYNDICATION_ATTRIBUTE_MAPPING_DETAILS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ATTR_CATEGORIES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ATTR_CATEGORIES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_MARKETING_RECOMMENDATION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_MARKETING_RECOMMENDATION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_ASSORTMENTS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_ASSORTMENTS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_ASSORTMENT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_ASSORTMENT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.EDIT_ASSORTMENT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.EDIT_ASSORTMENT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_ASSORTMENT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.DELETE_ASSORTMENT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.ADD_SKUS_TO_ASSORTMENT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.ADD_SKUS_TO_ASSORTMENT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.REMOVE_SKUS_FROM_ASSORTMENT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.REMOVE_SKUS_FROM_ASSORTMENT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CHANNELS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CHANNELS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CHANNEL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CHANNEL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_CHANNEL] = {
    METHOD: API_METHOD.POST,
    URL: AMAZE_API_URLS.CREATE_CHANNEL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.DELETE_CHANNEL] = {
    METHOD: API_METHOD.DELETE,
    URL: AMAZE_API_URLS.DELETE_CHANNEL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CHANNEL_FOR_CATALOG_CREATION] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CHANNEL_FOR_CATALOG_CREATION,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CATALOG_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_CHILD_NODES] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CATALOG_CHILD_NODES,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BRIDGE_CATALOG_NODES_SEARCH] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BRIDGE_CATALOG_NODES_SEARCH,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CHANGE_CHANNEL_STATE] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CHANGE_CHANNEL_STATE,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.BUILD_CHANNEL] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.BUILD_CHANNEL,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.VALIDATE_MAP] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.VALIDATE_MAP,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.CREATE_NEW_MAP] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.CREATE_NEW_MAP,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BACKUP_MAPS_COUNT] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BACKUP_MAPS_COUNT,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_BACKUP_MAPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_BACKUP_MAPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.RESTORE_BACKUP_MAPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.RESTORE_BACKUP_MAPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_AMAZE_CATALOG_DETAILS_FROM_BRIDGE_CATALOG] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_AMAZE_CATALOG_DETAILS_FROM_BRIDGE_CATALOG,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_NODE_MAPS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_NODE_MAPS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_PRE_TRANSFORM_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_PRE_TRANSFORM_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

APIS[AMAZE_API_NAMES.GET_TRANSFORMED_SKUS] = {
    METHOD: API_METHOD.GET,
    URL: AMAZE_API_URLS.GET_TRANSFORMED_SKUS,
    URL_PARAMS: [],
    QUERY_PARAMS: []
};

export const AMAZE_APIS = APIS;
