export enum AMAZE_STORE_STATES {
	APP_STATE                        = "appState",
	ASSORTMENT_STATE                 = "assortmentState",
	CATALOG_STATE                    = "catalogState",
	CHANNEL_STATE                    = "channelState",
	DAM_STATE                        = "damState",
	DASHBOARD_STATE                  = "dashboardState",
	DOMAINS_STATE                    = "domainsState",
	GRID_STATE                       = "gridState",
	GEN_AI_STATE                     = "genAiState",
	IMPORT_STATE                     = "importState",
	LANGUAGE_STATE                   = "languageState",
	MULTI_CHANNEL_DASHBOARD_STATE    = "channelsDashboardState",
	PRODUCT_DASHBOARD_STATE          = "productsDashboardState",
	PRODUCT_SEARCH_STATE             = "productSearchState",
	REPORTS_DASHBOARD_STATE          = "reportsDashboardState",
	REVIEW_DASHBOARD_STATE           = "reviewDashboardState",
	SOCKET_STATE                     = "socketState",
	STYLE_GUIDE_REPORT_STATE         = "styleGuideReportState",
}
