import { AMAZE_TERMS } from "@app/models/enums/amaze-terms.enums";

export const SIDENAV_LABELS = {
	"ADMIN"                       : "Admin",
	"EXTERNAL_FILE_LOCATION"      : "External File Location",
	"HELP"                        : "Help",
	"LOGOUT"                      : "Logout",
	"ROLE_MANAGEMENT"             : `${AMAZE_TERMS.ROLE} ${AMAZE_TERMS.MANAGEMENT}`,
	"SECURITY"                    : AMAZE_TERMS.SECURITY,
	"USER_GROUPS_MANAGEMENT"      : `${AMAZE_TERMS.USER} ${AMAZE_TERMS.GROUPS} ${AMAZE_TERMS.MANAGEMENT}`,
	"USER_MANAGEMENT"             : `${AMAZE_TERMS.USER} ${AMAZE_TERMS.MANAGEMENT}`,
    "ADVANCED_SKU_SEARCH"         : `Advanced ${AMAZE_TERMS.SKU} Search`,
    "ALL_CATALOGS"                : `All ${AMAZE_TERMS.CATALOGS}`,
    "ALL_CHANNELS"                : `All ${AMAZE_TERMS.CHANNELS}`,
    "API_MANAGEMENT"              : `API ${AMAZE_TERMS.MANAGEMENT}`,
    "ASSORTMENTS"                 : AMAZE_TERMS.ASSORTMENTS,
    "BATCH_EDIT_OPERATIONS"       : "Batch Edit Operations",
    "BATCH_EDIT_TEMPLATE"         : "Batch Edit Template",
    "BRIDGE_SYNCHRONIZATION"      : `${AMAZE_TERMS.BRIDGE} Synchronization`,
    "CATALOG_EXPORT"              : `${AMAZE_TERMS.CATALOG} ${AMAZE_TERMS.EXPORT}`,
    "CATALOG_IMPORT"              : `${AMAZE_TERMS.CATALOG} ${AMAZE_TERMS.IMPORT}`,
    "CATALOG"                     : AMAZE_TERMS.CATALOG,
    "CHANNELS_DASHBOARD"          : `Multi ${AMAZE_TERMS.CHANNEL} ${AMAZE_TERMS.DASHBOARD}`,
    "CHANNELS"                    : AMAZE_TERMS.CHANNELS,
    "CONFIGURE_CATALOG"           : `${AMAZE_TERMS.CONFIGURE} ${AMAZE_TERMS.CATALOG}`,
    "CONNECTORS"                  : "Connectors",
    "CUSTOM_EXPORT_TEMPLATE"      : "Custom Export Template",
    "DIGITAL_ASSET_IMPORT"        : `${AMAZE_TERMS.DIGITAL_ASSET} ${AMAZE_TERMS.IMPORT}`,
    "DIGITAL_ASSET_LIBRARY"       : `${AMAZE_TERMS.DIGITAL_ASSET} Library`,
    "DIGITAL_ASSET"               : AMAZE_TERMS.DIGITAL_ASSET,
	"DOMAINS"                     : AMAZE_TERMS.DOMAINS,
    "EXPORT"                      : AMAZE_TERMS.EXPORT,
    "FORMULA_MASTER"              : "Formula Master",
	"GEN_AI_RULES"                : AMAZE_TERMS.GEN_AI_RULES,
    "IMPORT_TEMPLATE"             : `${AMAZE_TERMS.IMPORT} Template`,
    "IMPORT"                      : AMAZE_TERMS.IMPORT,
    "LAUNCH_CHANNEL"              : `Launch ${AMAZE_TERMS.CHANNEL}`,
    "LOOKUP_TABLE_MASTER"         : "Lookup Table Master",
    "PDP_TEMPLATE"                : "PDP Template",
    "PRODUCT_DASHBOARD"           : `${AMAZE_TERMS.PRODUCT} ${AMAZE_TERMS.DASHBOARD}`,
    "PRODUCTS"                    : AMAZE_TERMS.PRODUCTS,
    "QUALITY_METRICS"             : "Quality Metrics",
    "REALTIME_SYNC_LINKAGES"      : "Realtime Sync Linkages",
    "REVIEW_DASHBOARD"            : `Review ${AMAZE_TERMS.DASHBOARD}`,
    "SKU_ATTRIBUTE_LOCK"          : `${AMAZE_TERMS.SKU} ${AMAZE_TERMS.ATTRIBUTE} Lock`,
    "STYLE_GUIDE"                 : "Style Guide",
    "SYNCHRONIZATION_REQUESTS"    : "Synchronization Requests",
    "VALIDATION_FAILURE"          : "Validation Failure",
    "VIEW_MY_PRODUCTS"            : `View My ${AMAZE_TERMS.PRODUCTS}`,
    "WORKFLOW"                    : "Workflows"
};
